---
title: "R Notebook"
output: html_notebook
---
#Author: Yufei Zhao, Vassily Carantino

#Libraries
```{r}
packages.used=c("leaflet","geojsonio","knitr","dplyr","maps","ggmaps")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}
library(leaflet)
library(geojsonio)
library(knitr)
library(dplyr)
library(maps)
library(ggmap)
```


```{r setup}
# Please change the file path !!
knitr::opts_knit$set(root.dir = '/tmp')
opts_knit$set(root.dir= 'C:/Users/vc2434/Desktop/Fall2017-project2-fall2017-project2-grp1-master/')
#opts_knit$set(root.dir = '/home/vassily/Desktop/Columbia/Fall 2017/Applied Data Science/Project 2/Fall2017-project2-fall2017-project2-grp1/')
```


# Read Data Bases
```{r}
#read Data Bases and create DF
setwd('C:/Users/vc2434/Desktop/Fall2017-project2-fall2017-project2-grp1-master/')
folder.path=paste0(getwd(),"/data")
schools<-read.csv(file.path(folder.path,"SchoolDirectory.csv"), header = TRUE, stringsAsFactors = FALSE)
rental<-read.csv(file.path(folder.path,"final_rental_data.csv"), header = TRUE, stringsAsFactors = FALSE)
sales<-read.csv(file.path(folder.path,"final_sale_data.csv"), header = TRUE, stringsAsFactors = FALSE)
crimes<-read.csv(file.path(folder.path,"final_crime.csv"), header = TRUE, stringsAsFactors = FALSE)
restaurants<-read.csv(file.path(folder.path,"restaurant_data.csv"), header = TRUE, stringsAsFactors = FALSE)
subways<-read.csv(file.path(folder.path,"subwaystation.csv"), header = TRUE, stringsAsFactors = FALSE)
galleries<-read.csv(file.path(folder.path,"art_gallery_data.csv"), header = TRUE, stringsAsFactors = FALSE)
theatres<-read.csv(file.path(folder.path,"theatre_data.csv"), header = TRUE, stringsAsFactors = FALSE)
hospitals<-read.csv(file.path(folder.path,"hospital.csv"), header = TRUE, stringsAsFactors = FALSE)
```

# Find LAT/LONG from address using ggmap API:
this is limited to 2500 request a day, so we will run it in two times to get the schools position.
 
```{r}

schools$location <- paste0(schools$MAILING.ADDRESS, ", ", schools$MAIL.CITY, ", NY ", schools$ZIP)
schools_trunc<-schools[1:2000,]
geo <- geocode(location = schools_trunc$location, output="latlon", source="google")
schools_trunc$long <- geo$lon
schools_trunc$lat <- geo$lat

write.csv(schools_trunc, file = "School_with_location.csv")

```


# Create Icons
here we create different icon to use for the different data points 
```{r}
image.path=paste0(getwd(),"/images")
icon_school <- makeIcon(
  iconUrl = file.path(image.path,"school.png"),
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

icon_hospital <- makeIcon(
  iconUrl = file.path(image.path,"hospital.png"),
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

icon_subway <- makeIcon(
  iconUrl = file.path(image.path,"subway.png"),
  iconWidth = 20, iconHeight = 20,
  iconAnchorX = 10, iconAnchorY = 10
)

```


# Plot Markers
Here we plot the markers the user choose
```{r}
#These Booleans will be controlled via the Shiny UI 
show_schools=TRUE
show_crimes=TRUE
show_restaurants=TRUE
show_subways=TRUE
show_galleries=TRUE
show_theatres=TRUE
show_hospitals=TRUE

if(show_schools==TRUE){  
  
}

if(show_crimes==TRUE){
  m<- addMarkers(m, data=crimes, clusterOptions = markerClusterOptions()) #play with the options  
}

if(show_restaurants==TRUE){
  
  
}

if(show_galleries==TRUE){
  
  
}

if(show_theatres==TRUE){
  
  
}

if(show_hospitals==TRUE){  
  m <- addMarkers(m, data=hospitals, lat = ~Latitude, lng = ~Longitude, popup = ~as.character(Facility.Name), label = ~as.character(Facility.Name), icon =icon_hospital)  
}

if(show_subways==TRUE){
  m<- addMarkers(m, data = subway, lat = ~Lat, lng = ~Long, popup = ~as.character(NAME), label = ~as.character(NAME), icon=icon_subway)  
}
```


```{r}

nycounties <- geojson_read(file.path(folder.path,"nyczip.geojson"), what = "sp")


```



```{r}
library(dplyr)
df2 <- df%>% na.omit
df2$NTA <-  trimws(df2$NTA)
df2$count <- rep(1, nrow(df2))
by_NTA <- group_by(df2, NTA, count)
school <- as.data.frame(summarise(by_NTA, total = sum(count)))
school$count<-NULL
```

```{r}
nta<-as.character(nycounties@data$NTAName)
sch <- rep(NA, length(nta))

for(i in 1: length(nta)){
  if(nta[i]%in% school$NTA){
    sch[i] <- school$total[nta[i] == school$NTA]
  }
  else{
    sch[i] <- 0
  }
  
}
nycounties@data$school <- sch
```

```{r}
qpal <- colorFactor("Blues", nycounties@data$school)
```


```{r}
leaflet(nycounties) %>% 
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 1.0, label = ~ paste(NTAName,school, sep =" & "),
     highlightOptions = highlightOptions(color = "red", weight = 2,
      bringToFront = TRUE),fillColor = ~qpal(school)) %>% addTiles() %>% addMarkers(lng = df2$Longitude, lat = df2$Latitude, label = df2$School)
```

