---
title: "R Notebook"
output: html_notebook
---
#Author: Yufei Zhao, Vassily Carantino

```{r setup}
# Please change the file path !!
knitr::opts_knit$set(root.dir = '/tmp')
opts_knit$set(root.dir = '/home/vassily/Desktop/Columbia/Fall 2017/Applied Data Science/Project 2/Fall2017-project2-fall2017-project2-grp1/')
```

#Libraries
```{r}
packages.used=c("leaflet","geojsonio")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}
library(leaflet)
library(geojsonio)
```



```{r}
# change the file path
#setwd("/Users/zhaox694/Desktop/ADS/Fall2017-project2-fall2017-project2-grp1/data")
#setwd("./Fall2017-project2-fall2017-project2-grp1/data")
```

```{r}
#read school data
folder.path=paste0(getwd(),"/data")
df<-read.csv(file.path(folder.path,"SchoolDirectory.csv"), header = TRUE, stringsAsFactors = FALSE)
```


```{r}
#school <-as.character(df$School)
#leaflet(data=df) %>% addTiles() %>% addMarkers(lng = ~Longitude,lat = ~Latitude, label = school )%>%addPolygons(lng = ~Longitude,lat = ~Latitude)
```


```{r}
library(geojsonio)
nycounties <- geojson_read(file.path(folder.path,"nyczip.geojson"), what = "sp")
```



```{r}
library(dplyr)
df2 <- df%>% na.omit
df2$NTA <-  trimws(df2$NTA)
df2$count <- rep(1, nrow(df2))
by_NTA <- group_by(df2, NTA, count)
school <- as.data.frame(summarise(by_NTA, total = sum(count)))
school$count<-NULL
```

```{r}
nta<-as.character(nycounties@data$NTAName)
sch <- rep(NA, length(nta))

for(i in 1: length(nta)){
  if(nta[i]%in% school$NTA){
    sch[i] <- school$total[nta[i] == school$NTA]
  }
  else{
    sch[i] <- 0
  }
  
}
nycounties@data$school <- sch
```

```{r}
qpal <- colorFactor("Blues", nycounties@data$school)
```


```{r}
leaflet(nycounties) %>% addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 1.0, label = ~ paste(NTAName,school, sep =" & "),
     highlightOptions = highlightOptions(color = "red", weight = 2,
      bringToFront = TRUE),fillColor = ~qpal(school)) %>% addTiles() %>% addMarkers(lng = df2$Longitude, lat = df2$Latitude, label = df2$School)
```

