---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(leaflet)
library(dplyr)
library(geojsonio)
library(htmltools)
```




1: read file in
```{r}
nycounties <- geojson_read("../data/nyczip.geojson", what = "sp")
```


# hospital data
```{r}
hospital <- read.csv("../data/final_hospital.csv", header=TRUE, stringsAsFactors = FALSE)
hospital$Longitude <- hospital$Longitude*(-1) # correct the longitugde
```


# art gallery data
```{r}
art <- read.csv("../data/final_art_gallery.csv", header=TRUE, stringsAsFactors = FALSE)

coord <- sapply(art$the_geom, function(x) {
  substr(x, 8, nchar(x)-1)
}) %>% as.character()
values <- strsplit(coord, split=" ") %>% unlist()
art_long <- NULL
art_lat <- NULL
for(i in 1:(length(values)/2)){
  art_long <- c(art_long,values[i*2-1])
  art_lat <- c(art_lat, values[i*2])
}
art_long <- art_long %>% as.numeric()
art_lat <- art_lat %>% as.numeric()
art$longitude <- art_long
art$latitude <- art_lat
```

# theatre data
```{r}
theatre <- read.csv("../data/final_theatre.csv", header=TRUE, stringsAsFactors = FALSE)

coord <- sapply(theatre$the_geom, function(x) {
  substr(x, 8, nchar(x)-1)
}) %>% as.character()
values <- strsplit(coord, split=" ") %>% unlist()
theatre_long <- NULL
theatre_lat <- NULL
for(i in 1:(length(values)/2)){
  theatre_long <- c(theatre_long,values[i*2-1])
  theatre_lat <- c(theatre_lat, values[i*2])
}
theatre_long <- theatre_long %>% as.numeric()
theatre_lat <- theatre_lat %>% as.numeric()
theatre$longitude <- theatre_long
theatre$latitude <- theatre_lat
```


# subway data
```{r}
subway <- read.csv("../data/subwaystation.csv", header=TRUE, stringsAsFactors = FALSE)
```

# crime data
```{r}
crime <- read.csv("../data/final_crime.csv", header=TRUE, stringsAsFactors = FALSE)
crime <- crime %>% na.omit() 
```

# sales data
```{r}
sales <- read.csv("../data/final_sale.csv", header=TRUE, stringsAsFactors = FALSE)
```

# rental data
```{r}
rental <- read.csv("../data/final_rental.csv", header=TRUE, stringsAsFactors = FALSE)
```


2 make the base map      color = "#444444"
```{r}
basemap <- leaflet(nycounties) %>% addPolygons( color = "#BFA",weight = 1, smoothFactor = 0.5, opacity = 1.0, fillOpacity = 0.5, highlightOptions = highlightOptions(color = "red", weight = 2, bringToFront = TRUE)) %>% addTiles()
```



# Icon Maker
```{r}
IconMaker <- function(address){
      icon <- makeIcon(
      iconUrl = address,
      iconWidth = 30, iconHeight = 30,
      iconAnchorX = 0, iconAnchorY = 0)
}


hospitalIcon <- IconMaker("../fig/Hospital.png")

galleryIcon <- IconMaker("../fig/Gallery.png")

theatreIcon <- IconMaker("../fig/Theatre.png")

subwayIcon <- IconMaker("../fig/Subway.png")

crimeIcon <- IconMaker("../fig/Crime.png")

```



#Hospital map   
```{r}
pops_hospital <- paste0("<center><strong style='color:blue'>",hospital$Facility.Name,"</strong>","<br/>",hospital$Phone, "<br/>", hospital$address, "</center>")

basemap %>% addMarkers(lng = hospital$Longitude, lat = hospital$Latitude, clusterOptions = markerClusterOptions() , popup = pops_hospital, icon=hospitalIcon)
```



#Art map
```{r}
pops_art <- paste0("<center><strong style='color:blue'>",art$NAME,"</strong>","<br/>",paste(art$ADDRESS1, art$ADDRESS2), "</center>")

basemap %>% addMarkers(lng = art$longitude, lat = art$latitude,clusterOptions = markerClusterOptions() , popup = pops_art, icon=galleryIcon)
```

#Theatre map
```{r}
pops_theatre <- paste0("<center><strong style='color:blue'>",theatre$NAME,"</strong>","<br/>",paste(theatre$ADDRESS1, theatre$ADDRESS2), "</center>")
basemap %>% addMarkers(lng = theatre$longitude, lat = theatre$latitude,clusterOptions = markerClusterOptions() , popup = pops_theatre, icon=theatreIcon)
```

#Subway map
```{r}
pops_subway <- paste0("<center><strong style='color:blue'>",subway$NAME,"</strong>","<br/>",subway$LINE, "</center>")
basemap %>% addMarkers(lng = subway$Long, lat = subway$Lat,clusterOptions = markerClusterOptions(), popup = pops_subway, icon=subwayIcon)
```


#Crime map
```{r}
pops_crime <- paste0("<center><strong style='color:blue'>",crime$LAW_CAT_CD,"</strong>","<br/>",crime$BORO_NM, "</center>")
basemap %>% addMarkers(lng = crime$Longitude, lat = crime$Latitude,clusterOptions = markerClusterOptions(), popup = pops_crime, icon=crimeIcon)
```

# Sales map
```{r}
basemap %>% addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1.0, fillOpacity = 0.0)
```







# combination of art and hospiptal
```{r}
basemap %>% addMarkers(lng = hospital$Longitude, lat = hospital$Latitude, clusterOptions = markerClusterOptions() , popup = pops_hospital, icon=hospitalIcon)  %>% addMarkers(lng = art$longitude, lat = art$latitude,clusterOptions = markerClusterOptions() , popup = pops_art, icon=galleryIcon)
```

