```{r}
# Time Sries Data for Rent
rental_data <- read.csv("../data/final_rental.csv", header=TRUE, stringsAsFactors = TRUE)
rental_data <- rental_data[-c(1,2,3,4,5), ]
history <- rental_data[ ,-4]
predict <- rental_data[ ,4]
data <- cbind(history, predict)

TimeSeriesPlot_rent <- function(x,y) {
  zip <- data[data$RegionName == x, ]
  RoomNum <- t(zip[zip $ Bedroom == y, -c(1,2,3)])
  roomtimeseries <- ts(RoomNum,frequency = 12, start=c(2011,9))
  plot.ts(roomtimeseries, xlab= NULL, ylab="Price", col="red")
  title("price change from Sep 2011 to Sep 2017", sub = "zip code and room
        numbers", cex.main = 1, font.main= 4, col.main= "blue", cex.sub = 0.75,
        font.sub = 3, col.sub = "red")
}

#TimeSeriesPlot_rent(10025,1)
#TimeSeriesPlot_rent(10025,2)
# TimeSeriesPlot_rent(10025,3)
# TimeSeriesPlot_rent(10025,4)


# Time Series Data for sale
sale_data <- read.csv("../data/final_sale.csv", header=TRUE, stringsAsFactors = TRUE)
sale_data <- sale_data[-1, ]
history <- sale_data[ ,-3]
predict <- sale_data[ ,3]
data <- cbind(history, predict)

TimeSeriesPlot_sale <- function(x) {
  Rooms <- t(data[data$RegionName == x,-c(1,2) ])
  roomtimeseries <- ts(Rooms,frequency = 12, start=c(2011,9))
  plot.ts(roomtimeseries, xlab= NULL, ylab="Price", col="red")
  title("price change from Sep 2011 to Sep 2017", sub = "zip code and room
        numbers", cex.main = 1, font.main= 4, col.main= "blue", cex.sub = 0.75,
        font.sub = 3, col.sub = "red")
}

# TimeSeriesPlot_sale(10025)
# TimeSeriesPlot_sale(10001)

```

```{r}


```


```{r}

```



```{r}

```



```{r}

```


```{r}

```